#!/usr/bin/env python3
"""Cybermancy rulebook source inventory builder.

Phase 1 repository scanner for the Cybermancy rulebook publishing pipeline.

This scanner is deliberately read-only. It inventories source files, MkDocs
publication scope, generated documentation, print-normalization concerns,
dependencies, and generator/source drift. It does NOT decide canon authority
or rulebook inclusion; those remain Phase 2 editorial decisions.

Run from the Cybermancy repository root:
    python pyCybermancy/build-rulebook-inventory.py

Or:
    python pyCybermancy/build-rulebook-inventory.py --repo-root /path/to/cybermancy
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import html
import json
import os
import re
import runpy
import subprocess
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Iterable
from urllib.parse import unquote, urlparse

SCRIPT_VERSION = "0.2.3"
SCHEMA_VERSION = "cybermancy-rulebook-inventory-v0.2.3"
GENERATOR = "pyCybermancy/generate-docs.py"

DEFAULT_EXCLUDED_DIRS = {
    ".git", ".github", ".idea", ".vscode", ".venv", "venv", "env",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "node_modules", "site", "_site", "build", "dist",
}

TEXT_EXTENSIONS = {
    ".md", ".markdown", ".txt", ".rst", ".yml", ".yaml", ".json",
    ".csv", ".tsv", ".py", ".js", ".mjs", ".cjs", ".ts", ".tsx",
    ".jsx", ".html", ".htm", ".css", ".scss", ".toml", ".ini",
    ".cfg", ".xml", ".svg", ".tex", ".lua", ".sh", ".ps1",
}

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".avif"}
DATA_EXTENSIONS = {".json", ".csv", ".tsv", ".yml", ".yaml", ".toml", ".xml"}
CODE_EXTENSIONS = {".py", ".js", ".mjs", ".cjs", ".ts", ".tsx", ".jsx", ".lua", ".sh", ".ps1"}
CONFIG_BASENAMES = {
    "mkdocs.yml", "mkdocs.yaml", "mkdocs.player.yml", "mkdocs.gm.yml",
    "pyproject.toml", "requirements.txt", "package.json",
}

RE_HEADING = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)
RE_MD_IMAGE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+[\"'][^\"']*[\"'])?\)")
RE_MD_LINK = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)\s]+)(?:\s+[\"'][^\"']*[\"'])?\)")
RE_HTML_IMG = re.compile(r"<img\b[^>]*?\bsrc\s*=\s*[\"']([^\"']+)[\"'][^>]*>", re.I)
RE_HTML_LINK = re.compile(r"<a\b[^>]*?\bhref\s*=\s*[\"']([^\"']+)[\"'][^>]*>", re.I)
RE_HTML_TAG = re.compile(r"</?[A-Za-z][^>]*>")
RE_SNIPPET = re.compile(r"--8<--\s*[\"']([^\"']+)[\"']")
RE_JINJA_EXPR = re.compile(r"{{.*?}}", re.S)
RE_JINJA_STMT = re.compile(r"{%.*?%}", re.S)
RE_LOAD_CSV = re.compile(r"\bload_csv\s*\(\s*[\"']([^\"']+)[\"']")
# Match the actual include-markdown plugin syntax; do not treat prose like
# "may include: Environmental Events" as an include directive.
RE_INCLUDE_MD = re.compile(
    r"""{%\s*include-markdown\s+["']([^"']+)["'][^%]*%}""",
    re.I | re.S,
)
RE_ADMONITION = re.compile(r"^\s*(?:!!!|\?\?\?)\s+", re.MULTILINE)
RE_TABS = re.compile(r'^\s*===\s+["\']', re.MULTILINE)
RE_ATTR_LIST = re.compile(r"\{[^{}]*(?:\.|#|:)[^{}]*\}")
RE_GENERATED = re.compile(
    r"\b(?:auto[- ]?generated|generated by|do not edit|do not modify|generator-owned|generated file)\b",
    re.I,
)
RE_GENERATOR_OWNER = re.compile(r"(?:generated by|generator)\s*[:=-]?\s*`?([^\n`]+)", re.I)
RE_MKDOCS_MD_PATH = re.compile(r"(?P<path>[A-Za-z0-9_./ -]+\.md)\b")
RE_RAW_URL = re.compile(r"https?://[^\s<>)\]}]+", re.I)
RE_DOCS_DIR = re.compile(r"^\s*docs_dir\s*:\s*[\"']?([^\"'#\n]+)", re.M)
RE_WORD = re.compile(r"\b[\w’'-]+\b", re.UNICODE)

DYNAMIC_FEATURES = {
    "mkdocs-snippets", "include-markdown", "jinja-expression",
    "jinja-statement", "load-csv",
}


@dataclass
class SiteConfig:
    site: str
    config_path: str
    docs_dir: str
    nav_members: set[str] = field(default_factory=set)
    nav_paths: dict[str, list[str]] = field(default_factory=dict)


@dataclass
class InventoryItem:
    path: str
    extension: str
    kind: str
    source_family: str
    audience: str
    content_scope: str
    authorship: str
    generator_owner: str = ""
    generator_type: str = ""
    title: str = ""
    headings: list[dict] = field(default_factory=list)
    word_count: int = 0
    mkdocs_features: list[str] = field(default_factory=list)
    normalization_flags: list[str] = field(default_factory=list)
    transclusions: list[str] = field(default_factory=list)
    includes: list[str] = field(default_factory=list)
    jinja_expression_count: int = 0
    jinja_statement_count: int = 0
    html_tag_count: int = 0
    images: list[str] = field(default_factory=list)
    internal_links: list[str] = field(default_factory=list)
    external_links: list[str] = field(default_factory=list)
    data_dependencies: list[str] = field(default_factory=list)
    site_targets: list[str] = field(default_factory=list)
    nav_targets: list[str] = field(default_factory=list)
    nav_paths: list[str] = field(default_factory=list)
    size_bytes: int = 0
    sha256: str = ""
    foundry_record_type: str = ""
    organizational: bool = False
    known_exceptions: list[str] = field(default_factory=list)
    review_flags: list[str] = field(default_factory=list)


def norm_rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        try:
            return path.read_text(encoding="utf-8-sig")
        except UnicodeDecodeError:
            return None
    except OSError:
        return None


def clean_heading(s: str) -> str:
    s = re.sub(r"\s+#+\s*$", "", s).strip()
    s = re.sub(r"`([^`]*)`", r"\1", s)
    s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)
    return s


def first_markdown_title(text: str) -> str:
    for m in RE_HEADING.finditer(text):
        if len(m.group(1)) == 1:
            return clean_heading(m.group(2))
    return ""


def extract_headings(text: str) -> list[dict]:
    return [
        {"level": len(m.group(1)), "text": clean_heading(m.group(2))}
        for m in RE_HEADING.finditer(text)
    ]


def is_foundry_folder_obj(obj: object) -> bool:
    """Return True for Foundry VTT folder records unpacked into JSON.

    Foundry pack-folder records use a canonical `_key` beginning with
    `!folders!`. Their other fields can resemble Item records, so `_key`
    is the reliable discriminator.
    """
    return isinstance(obj, dict) and str(obj.get("_key") or "").startswith("!folders!")


def parse_json_object(text: str | None) -> dict | None:
    if not text:
        return None
    try:
        obj = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None
    return obj if isinstance(obj, dict) else None


def is_templated_target(target: str) -> bool:
    """MkDocs/Jinja links are templates, not literal filesystem dependencies."""
    return "{{" in target or "{%" in target


def should_require_h1(rel: str) -> bool:
    """H1 is publication QA, not a Markdown syntax requirement.

    Require it only for standalone Markdown pages in the docs publication
    trees. Repository notes, generator sources, snippets, and other Markdown
    inputs are not automatically errors merely because they omit H1.
    """
    p = Path(rel)
    if p.suffix.lower() not in {".md", ".markdown"}:
        return False
    parts = p.parts
    return len(parts) >= 3 and parts[0] == "docs" and parts[1] in {
        "player-facing", "gm-facing", "_shared"
    }


def strip_fragment_query(target: str) -> str:
    return target.split("#", 1)[0].split("?", 1)[0]


def is_external(target: str) -> bool:
    parsed = urlparse(target)
    return parsed.scheme in {"http", "https", "mailto", "tel"} or target.startswith("//")


def unique_sorted(values: Iterable[str]) -> list[str]:
    return sorted({v.strip() for v in values if v and v.strip()})


def slugify(s: str) -> str:
    s = (s or "").strip().lower().replace(" ", "-")
    s = re.sub(r"[^a-z0-9\-]+", "-", s)
    return re.sub(r"-+", "-", s).strip("-") or "item"


def classify_kind(rel: str, suffix: str) -> str:
    base = Path(rel).name
    if base in CONFIG_BASENAMES or base.startswith("mkdocs."):
        return "config"
    if suffix in IMAGE_EXTENSIONS:
        return "asset"
    if suffix in CODE_EXTENSIONS:
        return "code"
    if suffix in DATA_EXTENSIONS:
        return "data"
    if suffix in {".md", ".markdown", ".rst", ".txt"}:
        return "document"
    if suffix in {".html", ".htm", ".css", ".scss", ".tex"}:
        return "presentation"
    return "other"


def classify_source_family(rel: str) -> str:
    p = rel.lower()
    if p.startswith("docs/player-facing/"):
        return "player"
    if p.startswith("docs/gm-facing/"):
        return "gm"
    if p.startswith("pycybermancy/") or p.startswith("scripts/"):
        return "generator"
    if p.startswith("docs/data/"):
        return "data"
    if p.startswith("docs/"):
        return "shared-docs"
    if Path(rel).name.startswith("mkdocs."):
        return "config"
    if p.startswith("packs/") or p.startswith("src/") or p.startswith("src-loadable/") or p.startswith("src-descriptors/"):
        return "structured-source"
    if any(p.startswith(prefix) for prefix in ("assets/", "art/", "images/", "icons/")):
        return "asset"
    return "repository"


def classify_audience(rel: str, source_family: str) -> str:
    if source_family == "player":
        return "player"
    if source_family == "gm":
        return "gm"
    if source_family in {"generator", "config"}:
        return "developer"
    if source_family in {"data", "structured-source", "shared-docs"}:
        return "shared"
    return "unknown"


def classify_content_scope(rel: str) -> str:
    p = rel.lower()
    if "/adventures/" in p or p.startswith("packs/adventures/"):
        return "campaign"
    if "/rules/" in p or "/system/" in p or "/items/" in p:
        return "system"
    if "/world/" in p or p.startswith("docs/_shared/world/"):
        return "setting"
    if "/meta/" in p or p.startswith("notes/") or p.startswith("pycybermancy/") or p.startswith("scripts/"):
        return "developer"
    if p.startswith(("src/packs/items/", "src/packs/system/", "src/packs/features/", "src/packs/adversaries/", "src/packs/environments/")):
        return "system"
    if p.startswith(("src-loadable/items/", "packs/items/", "packs/system/")):
        return "system"
    if p.startswith(("src/packs/actors/", "packs/adventures/")):
        return "campaign"
    return "unknown"


def parse_mkdocs_configs(root: Path) -> tuple[dict[str, SiteConfig], list[str]]:
    """Read docs_dir and nav membership from the two MkDocs configs.

    This remains dependency-free: the repository's current config format is
    simple enough that a lightweight parser is deterministic and sufficient.
    """
    sites: dict[str, SiteConfig] = {}
    warnings: list[str] = []
    for site, filename in (("player", "mkdocs.player.yml"), ("gm", "mkdocs.gm.yml")):
        cfg = root / filename
        if not cfg.exists():
            warnings.append(f"missing expected config: {filename}")
            continue
        text = read_text(cfg)
        if text is None:
            warnings.append(f"could not decode config: {filename}")
            continue
        m = RE_DOCS_DIR.search(text)
        docs_dir = (m.group(1).strip() if m else ("docs/player-facing" if site == "player" else "docs/gm-facing"))
        sc = SiteConfig(site=site, config_path=filename, docs_dir=Path(docs_dir).as_posix())
        current_labels: list[str] = []
        in_nav = False
        nav_indent = 0
        for raw_line in text.splitlines():
            line = raw_line.rstrip()
            indent = len(line) - len(line.lstrip(" "))
            if re.match(r"^\s*nav\s*:\s*$", line):
                in_nav = True
                nav_indent = indent
                current_labels = []
                continue
            if in_nav and line.strip() and indent <= nav_indent and not line.lstrip().startswith("-"):
                in_nav = False
            if not in_nav:
                continue

            label_match = re.match(r"^\s*-\s*([^:#\[\]{}]+):\s*$", line)
            if label_match:
                depth = max((indent - nav_indent) // 2, 0)
                label = label_match.group(1).strip(" -\t\"'")
                current_labels = current_labels[:depth] + [label]

            for mm in RE_MKDOCS_MD_PATH.finditer(line):
                raw_path = mm.group("path").strip().lstrip("/")
                chosen = f"{sc.docs_dir}/{raw_path}" if not raw_path.startswith("docs/") else raw_path
                sc.nav_members.add(chosen)
                labels = [x for x in current_labels if x.lower() != "nav"]
                if labels:
                    sc.nav_paths.setdefault(chosen, []).append(" > ".join(labels))
        sites[site] = sc
    return sites, warnings


def site_targets_for_path(rel: str, sites: dict[str, SiteConfig]) -> list[str]:
    out = []
    for site, cfg in sites.items():
        prefix = cfg.docs_dir.rstrip("/") + "/"
        if rel == cfg.docs_dir or rel.startswith(prefix):
            out.append(site)
    return sorted(out)


def site_for_path(rel: str, sites: dict[str, SiteConfig]) -> str | None:
    targets = site_targets_for_path(rel, sites)
    return targets[0] if len(targets) == 1 else None


def resolve_candidate(candidate: Path, root: Path) -> tuple[str, bool]:
    try:
        candidate = candidate.resolve()
        root_resolved = root.resolve()
        candidate.relative_to(root_resolved)
    except (OSError, ValueError):
        return candidate.as_posix(), False

    variants = [candidate]
    if candidate.suffix == "":
        variants += [candidate.with_suffix(".md"), candidate / "index.md"]
    found = next((p for p in variants if p.exists()), None)
    if found:
        return norm_rel(found, root), True
    try:
        return norm_rel(candidate, root), False
    except ValueError:
        return candidate.as_posix(), False


def resolve_local_dependency(source_rel: str, target: str, root: Path) -> tuple[str | None, bool]:
    """Resolve normal Markdown/HTML dependencies relative to the source document.

    A bare 'assets/...' path inside MkDocs content is relative to that document/site,
    not automatically to the repository root.
    """
    target = unquote(strip_fragment_query(html.unescape(target))).strip().strip("<>")
    if not target or target.startswith(("#", "mailto:", "tel:", "data:")) or is_external(target):
        return None, True
    if target.startswith("/"):
        candidate = root / target.lstrip("/")
    elif target.startswith(("docs/", "pyCybermancy/", "packs/", "src/", "src-loadable/", "src-descriptors/")):
        candidate = root / target
    else:
        candidate = (root / source_rel).parent / target
    return resolve_candidate(candidate, root)


def resolve_load_csv_dependency(source_rel: str, target: str, root: Path, sites: dict[str, SiteConfig]) -> tuple[str | None, bool]:
    """Resolve load_csv exactly as docs/include/load-csv.py does: docs_dir / rel_path."""
    target = unquote(strip_fragment_query(html.unescape(target))).strip().strip("<>")
    if not target:
        return None, True
    site = site_for_path(source_rel, sites)
    if site and site in sites:
        candidate = root / sites[site].docs_dir / target
    else:
        candidate = (root / source_rel).parent / target
    return resolve_candidate(candidate, root)


def strip_markup_for_word_count(text: str) -> str:
    t = re.sub(r"```.*?```", " ", text, flags=re.S)
    t = RE_HTML_TAG.sub(" ", t)
    t = re.sub(r"[#*_`>|{}\[\]()]", " ", t)
    return html.unescape(t)


def scan_text_features(rel: str, text: str, root: Path, sites: dict[str, SiteConfig]) -> dict:
    suffix = Path(rel).suffix.lower()
    headings = extract_headings(text) if suffix in {".md", ".markdown", ".rst"} else []
    title = first_markdown_title(text) if headings else ""
    transclusions = unique_sorted(RE_SNIPPET.findall(text))
    includes = unique_sorted(RE_INCLUDE_MD.findall(text))
    load_csv = unique_sorted(RE_LOAD_CSV.findall(text))
    md_images = [m.group(2) for m in RE_MD_IMAGE.finditer(text)]
    html_images = RE_HTML_IMG.findall(text)
    images = unique_sorted(md_images + html_images)

    internal_links: list[str] = []
    external_links: list[str] = []
    for m in RE_MD_LINK.finditer(text):
        target = m.group(2)
        (external_links if is_external(target) else internal_links).append(target)
    for target in RE_HTML_LINK.findall(text):
        (external_links if is_external(target) else internal_links).append(target)
    for raw in RE_RAW_URL.findall(text):
        external_links.append(raw.rstrip(".,;:"))

    features: list[str] = []
    if transclusions:
        features.append("mkdocs-snippets")
    if includes:
        features.append("include-markdown")
    if RE_JINJA_EXPR.search(text):
        features.append("jinja-expression")
    if RE_JINJA_STMT.search(text):
        features.append("jinja-statement")
    if load_csv:
        features.append("load-csv")
    if RE_ADMONITION.search(text):
        features.append("material-admonition")
    if RE_TABS.search(text):
        features.append("material-tabs")
    if RE_ATTR_LIST.search(text):
        features.append("attribute-list")
    html_count = len(RE_HTML_TAG.findall(text))
    if html_count:
        features.append("raw-html")

    unresolved: list[str] = []
    known_exceptions: list[str] = []
    resolved_dependencies: list[str] = []

    normal_deps = unique_sorted(transclusions + includes + images + internal_links)
    for dep in normal_deps:
        if is_templated_target(dep):
            known_exceptions.append("templated-local-dependency")
            continue
        resolved, exists = resolve_local_dependency(rel, dep, root)
        if resolved:
            resolved_dependencies.append(resolved)
            if not exists:
                unresolved.append(f"unresolved-local-dependency:{dep}")

    resolved_data: list[str] = []
    for dep in load_csv:
        resolved, exists = resolve_load_csv_dependency(rel, dep, root, sites)
        if resolved:
            resolved_data.append(resolved)
            if not exists:
                unresolved.append(f"unresolved-local-dependency:{dep}")

    generator_owner = ""
    gm = RE_GENERATOR_OWNER.search(text)
    if gm:
        generator_owner = gm.group(1).strip(" .")
    elif GENERATOR.lower() in text.lower():
        generator_owner = GENERATOR

    wc = len(RE_WORD.findall(strip_markup_for_word_count(text)))
    flags = list(unresolved)
    if should_require_h1(rel) and not title:
        flags.append("missing-h1-title")
    if suffix in {".md", ".markdown"} and wc < 12:
        flags.append("stub-document")

    normalization_flags = list(features)
    if html_count >= 20:
        normalization_flags.append("html-heavy")

    return {
        "headings": headings,
        "title": title,
        "word_count": wc,
        "transclusions": transclusions,
        "includes": includes,
        "jinja_expression_count": len(RE_JINJA_EXPR.findall(text)),
        "jinja_statement_count": len(RE_JINJA_STMT.findall(text)),
        "html_tag_count": html_count,
        "images": images,
        "internal_links": unique_sorted(internal_links),
        "external_links": unique_sorted(external_links),
        "data_dependencies": unique_sorted(load_csv + resolved_data + resolved_dependencies),
        "mkdocs_features": unique_sorted(features),
        "normalization_flags": unique_sorted(normalization_flags),
        "generator_owner": generator_owner,
        "known_exceptions": unique_sorted(known_exceptions),
        "review_flags": unique_sorted(flags),
    }


def walk_repo(root: Path) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in DEFAULT_EXCLUDED_DIRS and not d.startswith("."))
        for name in sorted(filenames):
            if name.startswith("."):
                continue
            yield Path(dirpath) / name


def git_commit(root: Path) -> str:
    try:
        p = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True,
        )
        return p.stdout.strip()
    except Exception:
        return ""


def discover_generator_families(root: Path) -> tuple[dict[str, dict], list[str]]:
    """Return generate-docs-managed publication families from its live CONFIG.

    generate-docs.py is executed with a non-main run name so its guarded CLI is
    not invoked. This lets the inventory scanner read the same CONFIG object the
    generator actually uses, including programmatic CONFIG additions and
    explicit Actor-family ``src_path`` / ``out_dir_name`` values.

    Returns ``({type_key: metadata}, warnings)``. Metadata contains:
      - kind
      - audiences
      - source_path
      - output_dirs (CONFIG audience -> path relative to docs/)
      - actor_type (when present)
    """
    generator_path = root / GENERATOR
    if not generator_path.exists():
        return {}, [f"missing expected generator: {GENERATOR}"]

    try:
        namespace = runpy.run_path(
            str(generator_path),
            run_name="_cybermancy_generate_docs_inventory_config",
        )
    except Exception as exc:
        return {}, [f"could not load generator CONFIG from {GENERATOR}: {exc}"]

    config = namespace.get("CONFIG")
    if not isinstance(config, dict):
        return {}, [f"CONFIG dictionary not found in {GENERATOR}"]

    families: dict[str, dict] = {}
    warnings: list[str] = []

    for type_key, cfg in config.items():
        if not isinstance(type_key, str) or not isinstance(cfg, dict):
            continue

        kind = str(cfg.get("kind") or "").strip()
        audiences = cfg.get("audiences") or []
        if not kind:
            warnings.append(f"generator family {type_key}: missing kind")
            continue
        if not isinstance(audiences, (list, tuple)) or not all(isinstance(a, str) for a in audiences):
            warnings.append(f"generator family {type_key}: invalid audiences")
            continue

        source_path = str(cfg.get("src_path") or "").strip()
        if not source_path:
            src_subdir = str(cfg.get("src_subdir") or type_key).strip()
            source_path = f"src/packs/{kind}/{src_subdir}"
        source_path = Path(source_path).as_posix().strip("/")

        output_dirs: dict[str, str] = {}
        out_dir_name = cfg.get("out_dir_name")
        if callable(out_dir_name):
            for audience in audiences:
                try:
                    out_dir = out_dir_name(audience, type_key)
                except Exception as exc:
                    warnings.append(
                        f"generator family {type_key}: could not resolve out_dir_name "
                        f"for {audience}: {exc}"
                    )
                    continue
                if out_dir:
                    output_dirs[audience] = Path(str(out_dir)).as_posix().strip("/")
        else:
            warnings.append(f"generator family {type_key}: missing callable out_dir_name")

        families[type_key] = {
            "kind": kind,
            "audiences": list(audiences),
            "source_path": source_path,
            "output_dirs": output_dirs,
            "actor_type": str(cfg.get("actor_type") or "").strip(),
        }

    return families, warnings


def discover_generator_types(root: Path) -> dict[str, str]:
    """Backward-compatible ``{type_key: kind}`` view of CONFIG-managed families."""
    families, _warnings = discover_generator_families(root)
    return {type_key: str(meta.get("kind") or "") for type_key, meta in families.items()}


def generated_output_info(
    rel: str,
    root: Path,
    generator_families: dict[str, dict],
) -> tuple[bool, str]:
    """Identify generated detail pages and CSV indexes from CONFIG output paths."""
    p = Path(rel)

    if (
        len(p.parts) == 3
        and p.parts[0] == "docs"
        and p.parts[1] == "data"
        and p.suffix.lower() == ".csv"
        and p.stem in generator_families
    ):
        return True, p.stem

    if p.name != "index.md":
        return False, ""

    for type_key, family in generator_families.items():
        for out_rel in family.get("output_dirs", {}).values():
            base = Path("docs") / out_rel
            try:
                tail = p.relative_to(base)
            except ValueError:
                continue
            if len(tail.parts) == 2 and tail.parts[-1] == "index.md":
                return True, type_key

    return False, ""


def read_source_records(
    root: Path,
    family_or_kind: dict | str,
    type_key: str | None = None,
) -> tuple[dict[str, str], dict[str, str]]:
    """Return (publication entities, Foundry folder records) keyed by slug.

    Preferred callers pass CONFIG-derived family metadata. The legacy
    ``(kind, type_key)`` form is retained for compatibility.
    """
    if isinstance(family_or_kind, dict):
        family = family_or_kind
        base = root / str(family.get("source_path") or "")
        actor_type = str(family.get("actor_type") or "").strip()
    else:
        kind = str(family_or_kind)
        if not type_key:
            return {}, {}
        base = root / "src" / "packs" / kind / type_key
        actor_type = ""

    entities: dict[str, str] = {}
    folders: dict[str, str] = {}
    if not base.exists():
        return entities, folders

    for source_path in sorted(base.rglob("*.json")):
        try:
            obj = json.loads(source_path.read_text(encoding="utf-8"))
        except Exception:
            continue

        name = obj.get("name")
        if not name:
            continue

        slug = slugify(str(name))
        if is_foundry_folder_obj(obj):
            folders[slug] = norm_rel(source_path, root)
            continue

        # Match generate-docs Actor filtering when actor_type is specified.
        if actor_type and str(obj.get("type") or "") != actor_type:
            continue

        entities[slug] = norm_rel(source_path, root)

    return entities, folders


def read_source_entities(
    root: Path,
    family_or_kind: dict | str,
    type_key: str | None = None,
) -> dict[str, str]:
    """Backward-compatible publication-entity view used by callers."""
    entities, _folders = read_source_records(root, family_or_kind, type_key)
    return entities


def discover_foundry_folders(
    root: Path,
    generator_families: dict[str, dict],
) -> dict[str, dict[str, str]]:
    """Map generator type -> {folder_slug: source_path} for Foundry folder JSON."""
    out: dict[str, dict[str, str]] = {}
    for type_key, family in generator_families.items():
        _entities, folders = read_source_records(root, family)
        out[type_key] = folders
    return out


def icon_dependency_type_slug(dep: str) -> tuple[str, str] | None:
    """Infer generator type and basename slug from an assets/icons dependency."""
    target = unquote(strip_fragment_query(html.unescape(dep))).replace("\\", "/")
    marker = "assets/icons/"
    if marker not in target:
        return None
    rest = target.split(marker, 1)[1].strip("/")
    parts = [p for p in rest.split("/") if p]
    if len(parts) < 2:
        return None
    type_key = parts[0]
    slug = slugify(Path(parts[-1]).stem)
    return type_key, slug


def reconcile_generator_outputs(
    root: Path,
    generator_families: dict[str, dict],
) -> list[dict]:
    """Reconcile each CONFIG-managed source family with its configured outputs."""
    rows: list[dict] = []

    for type_key, family in sorted(generator_families.items()):
        kind = str(family.get("kind") or "")
        entities, folders = read_source_records(root, family)
        expected = set(entities)
        folder_slugs = set(folders)

        for audience in family.get("audiences", []):
            out_rel = str(family.get("output_dirs", {}).get(audience, ""))
            actual: set[str] = set()
            if out_rel:
                out_base = root / "docs" / out_rel
                if out_base.exists():
                    actual = {
                        page.parent.name
                        for page in out_base.glob("*/index.md")
                        if page.is_file()
                    }

            organizational = sorted((actual - expected) & folder_slugs)
            missing = sorted(expected - actual)
            orphan = sorted(actual - expected - folder_slugs)
            rows.append({
                "audience": "player" if audience == "player-facing" else "gm",
                "type": type_key,
                "kind": kind,
                "source_path": str(family.get("source_path") or ""),
                "output_dir": f"docs/{out_rel}" if out_rel else "",
                "source_entities": len(expected),
                "foundry_folders": len(folder_slugs),
                "generated_pages": len(actual),
                "missing_generated_pages": missing,
                "organizational_generated_pages": organizational,
                "orphan_generated_pages": orphan,
            })

    return rows


def classify_authorship(text: str | None, kind: str, generated_output: bool) -> str:
    if generated_output:
        return "generated"
    if text is None:
        return "unknown"
    if RE_GENERATED.search(text):
        return "generated"
    if kind in {"document", "presentation", "config", "code", "data"}:
        return "hand-authored-or-source"
    return "unknown"


def add_title_collision_flags(items: list[InventoryItem]) -> list[dict]:
    title_map: dict[str, list[InventoryItem]] = defaultdict(list)
    for item in items:
        if item.kind == "document" and item.title and not item.organizational:
            title_map[item.title.casefold()].append(item)

    collisions: list[dict] = []
    for key, group in sorted(title_map.items()):
        if len(group) <= 1:
            continue
        paths = [i.path for i in group]
        categories = {"/".join(Path(i.path).parts[2:4]) for i in group if i.path.startswith("docs/")}
        audiences = {i.audience for i in group}

        # Same relative page mirrored between player and GM is low-risk; otherwise
        # duplicate titles can become anchor collisions in a merged rulebook.
        relative_after_audience = []
        for i in group:
            parts = Path(i.path).parts
            if len(parts) >= 3 and parts[0] == "docs" and parts[1] in {"player-facing", "gm-facing"}:
                relative_after_audience.append("/".join(parts[2:]))
            else:
                relative_after_audience.append(i.path)
        mirrored = len(set(relative_after_audience)) == 1 and len(audiences) > 1
        if not mirrored:
            for item in group:
                item.review_flags = unique_sorted(item.review_flags + ["title-collision-candidate"])
        collisions.append({
            "title": group[0].title,
            "classification": "mirror" if mirrored else "collision-candidate",
            "paths": sorted(paths),
            "categories": sorted(categories),
        })
    return collisions


def build_inventory(root: Path) -> dict:
    sites, config_warnings = parse_mkdocs_configs(root)
    generator_families, generator_warnings = discover_generator_families(root)
    config_warnings.extend(generator_warnings)
    generator_types = {
        type_key: str(meta.get("kind") or "")
        for type_key, meta in generator_families.items()
    }
    foundry_folders = discover_foundry_folders(root, generator_families)
    reconciliation = reconcile_generator_outputs(root, generator_families)
    items: list[InventoryItem] = []

    for path in walk_repo(root):
        rel = norm_rel(path, root)
        suffix = path.suffix.lower()
        try:
            raw = path.read_bytes()
        except OSError:
            continue
        kind = classify_kind(rel, suffix)
        source_family = classify_source_family(rel)
        audience = classify_audience(rel, source_family)
        content_scope = classify_content_scope(rel)
        generated_output, generator_type = generated_output_info(rel, root, generator_families)
        text = read_text(path) if suffix in TEXT_EXTENSIONS or kind in {"document", "config", "code", "data", "presentation"} else None
        authorship = classify_authorship(text, kind, generated_output)

        site_targets = site_targets_for_path(rel, sites)
        nav_targets = sorted(site for site, cfg in sites.items() if rel in cfg.nav_members)
        nav_paths = unique_sorted(
            nav_path
            for site in nav_targets
            for nav_path in sites[site].nav_paths.get(rel, [])
        )

        item = InventoryItem(
            path=rel,
            extension=suffix,
            kind=kind,
            source_family=source_family,
            audience=audience,
            content_scope=content_scope,
            authorship=authorship,
            generator_owner=GENERATOR if generated_output else "",
            generator_type=generator_type,
            size_bytes=len(raw),
            sha256=sha256_bytes(raw),
            site_targets=site_targets,
            nav_targets=nav_targets,
            nav_paths=nav_paths,
        )

        if generated_output and generator_type:
            parts = Path(rel).parts
            if parts and parts[-1] == "index.md" and len(parts) >= 2:
                output_slug = parts[-2]
                if output_slug in foundry_folders.get(generator_type, {}):
                    item.foundry_record_type = "folder-publication"
                    item.organizational = True
                    item.known_exceptions = unique_sorted(
                        item.known_exceptions + ["foundry-folder-generated-page"]
                    )

        if suffix == ".json" and rel.startswith("src/"):
            obj = parse_json_object(text)
            if is_foundry_folder_obj(obj):
                item.foundry_record_type = "folder"
                item.organizational = True
                item.known_exceptions = unique_sorted(item.known_exceptions + ["foundry-folder-record"])

        if text is not None and kind in {"document", "presentation"}:
            feat = scan_text_features(rel, text, root, sites)
            for k, v in feat.items():
                setattr(item, k, v)

            # A missing icon for a Foundry folder is intentional organizational
            # metadata, not missing publication art.
            retained_flags: list[str] = []
            for flag in item.review_flags:
                if not flag.startswith("unresolved-local-dependency:"):
                    retained_flags.append(flag)
                    continue
                dep = flag.split(":", 1)[1]
                parsed = icon_dependency_type_slug(dep)
                if parsed:
                    dep_type, dep_slug = parsed
                    if dep_slug in foundry_folders.get(dep_type, {}):
                        item.known_exceptions = unique_sorted(
                            item.known_exceptions + ["foundry-folder-icon-reference"]
                        )
                        continue
                retained_flags.append(flag)
            item.review_flags = unique_sorted(retained_flags)
            if item.organizational:
                item.review_flags = [
                    f for f in item.review_flags
                    if f not in {"stub-document", "missing-h1-title"}
                ]

            if generated_output:
                item.generator_owner = GENERATOR
                item.generator_type = generator_type

        items.append(item)

    items.sort(key=lambda i: i.path.lower())

    title_collisions = add_title_collision_flags(items)

    # Flag missing/orphan generator pages on the corresponding inventory entries.
    by_path = {i.path: i for i in items}
    for rec in reconciliation:
        output_dir = str(rec.get("output_dir") or "").rstrip("/")
        for slug in rec["orphan_generated_pages"]:
            p = f"{output_dir}/{slug}/index.md" if output_dir else ""
            if p in by_path:
                by_path[p].review_flags = unique_sorted(by_path[p].review_flags + ["orphan-generated-page"])
        for slug in rec.get("organizational_generated_pages", []):
            p = f"{output_dir}/{slug}/index.md" if output_dir else ""
            if p in by_path:
                by_path[p].organizational = True
                by_path[p].foundry_record_type = "folder-publication"
                by_path[p].known_exceptions = unique_sorted(
                    by_path[p].known_exceptions + ["foundry-folder-generated-page"]
                )
        # Missing pages have no InventoryItem, so they remain in generator_reconciliation.

    sha_map: dict[str, list[InventoryItem]] = defaultdict(list)
    for i in items:
        if i.sha256:
            sha_map[i.sha256].append(i)
    duplicate_groups = [g for g in sha_map.values() if len(g) > 1]
    duplicate_by_kind = Counter()
    for group in duplicate_groups:
        for i in group:
            duplicate_by_kind[i.kind] += 1

    counts = {
        "total_files": len(items),
        "by_kind": dict(sorted(Counter(i.kind for i in items).items())),
        "by_source_family": dict(sorted(Counter(i.source_family for i in items).items())),
        "by_audience": dict(sorted(Counter(i.audience for i in items).items())),
        "by_content_scope": dict(sorted(Counter(i.content_scope for i in items).items())),
        "by_authorship": dict(sorted(Counter(i.authorship for i in items).items())),
        "documents": sum(i.kind == "document" for i in items),
        "documents_player_site": sum(i.kind == "document" and "player" in i.site_targets for i in items),
        "documents_gm_site": sum(i.kind == "document" and "gm" in i.site_targets for i in items),
        "documents_player_nav": sum(i.kind == "document" and "player" in i.nav_targets for i in items),
        "documents_gm_nav": sum(i.kind == "document" and "gm" in i.nav_targets for i in items),
        "generated_documents": sum(i.kind == "document" and i.authorship == "generated" for i in items),
        "hand_authored_documents": sum(i.kind == "document" and i.authorship == "hand-authored-or-source" for i in items),
        "dynamic_documents": sum(
            i.kind == "document" and bool(set(i.mkdocs_features) & DYNAMIC_FEATURES)
            for i in items
        ),
        "documents_requiring_normalization": sum(
            i.kind == "document" and bool(i.normalization_flags)
            for i in items
        ),
        "stub_documents": sum(i.kind == "document" and "stub-document" in i.review_flags for i in items),
        "foundry_folder_records": sum(i.foundry_record_type == "folder" for i in items),
        "organizational_files": sum(i.organizational for i in items),
        "known_exception_files": sum(bool(i.known_exceptions) for i in items),
        "flagged_files": sum(bool(i.review_flags) for i in items),
        "unresolved_dependency_files": sum(
            any(f.startswith("unresolved-local-dependency:") for f in i.review_flags)
            for i in items
        ),
        "duplicate_content_groups": len(duplicate_groups),
        "files_in_duplicate_content_groups": sum(len(g) for g in duplicate_groups),
        "duplicate_content_files_by_kind": dict(sorted(duplicate_by_kind.items())),
    }

    review_flag_counts = Counter(flag for item in items for flag in item.review_flags)
    known_exception_counts = Counter(flag for item in items for flag in item.known_exceptions)
    feature_counts = Counter(feature for item in items for feature in item.mkdocs_features)
    normalization_flag_counts = Counter(flag for item in items for flag in item.normalization_flags)

    return {
        "schema": SCHEMA_VERSION,
        "script_version": SCRIPT_VERSION,
        "repository": {
            "root_name": root.name,
            "git_commit": git_commit(root),
        },
        "mkdocs_sites": {
            site: {
                "config": cfg.config_path,
                "docs_dir": cfg.docs_dir,
                "nav_member_count": len(cfg.nav_members),
            }
            for site, cfg in sites.items()
        },
        "counts": counts,
        "mkdocs_config_warnings": sorted(config_warnings),
        "mkdocs_feature_counts": dict(sorted(feature_counts.items())),
        "normalization_flag_counts": dict(sorted(normalization_flag_counts.items())),
        "review_flag_counts": dict(sorted(review_flag_counts.items())),
        "known_exception_counts": dict(sorted(known_exception_counts.items())),
        "generator_types": dict(sorted(generator_types.items())),
        "generator_families": {
            type_key: {
                "kind": family.get("kind", ""),
                "audiences": family.get("audiences", []),
                "source_path": family.get("source_path", ""),
                "output_dirs": family.get("output_dirs", {}),
                "actor_type": family.get("actor_type", ""),
            }
            for type_key, family in sorted(generator_families.items())
        },
        "generator_reconciliation": reconciliation,
        "title_collisions": title_collisions,
        "items": [asdict(i) for i in items],
    }


def write_json(inv: dict, out: Path) -> None:
    out.write_text(json.dumps(inv, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_csv(inv: dict, out: Path) -> None:
    fields = [
        "path", "extension", "kind", "source_family", "audience", "content_scope",
        "authorship", "generator_owner", "generator_type", "title", "word_count",
        "site_targets", "nav_targets", "nav_paths", "heading_count",
        "mkdocs_features", "normalization_flags", "transclusions", "includes", "jinja_expression_count",
        "jinja_statement_count", "html_tag_count", "images", "internal_links",
        "external_links", "data_dependencies", "size_bytes", "sha256",
        "foundry_record_type", "organizational", "known_exceptions", "review_flags",
    ]
    with out.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for i in inv["items"]:
            row = dict(i)
            row["heading_count"] = len(i["headings"])
            for key in [
                "site_targets", "nav_targets", "nav_paths", "mkdocs_features", "normalization_flags",
                "transclusions", "includes", "images", "internal_links",
                "external_links", "data_dependencies", "known_exceptions", "review_flags",
            ]:
                row[key] = " | ".join(i[key])
            row.pop("headings", None)
            w.writerow({k: row.get(k, "") for k in fields})


def md_table(rows: list[tuple[str, object]]) -> str:
    lines = ["| Metric | Count |", "|---|---:|"]
    lines.extend(f"| {k} | {v} |" for k, v in rows)
    return "\n".join(lines)


def write_report(inv: dict, out: Path) -> None:
    c = inv["counts"]
    lines = [
        "# Cybermancy Rulebook Source Inventory",
        "",
        f"Schema: `{inv['schema']}`  ",
        f"Scanner: `{inv['script_version']}`  ",
        f"Git commit: `{inv['repository']['git_commit'] or 'unavailable'}`",
        "",
        "## Scope",
        "",
        "This is a read-only corpus inventory. It identifies source types, publication audiences,",
        "generated content, MkDocs-specific constructs, dependencies, and generator/source drift.",
        "It does **not** decide canonical authority or rulebook inclusion; those are Phase 2 decisions.",
        "",
        "## Summary",
        "",
        md_table([
            ("Files scanned", c["total_files"]),
            ("Documents", c["documents"]),
            ("Player-site documents", c["documents_player_site"]),
            ("GM-site documents", c["documents_gm_site"]),
            ("Player nav entries", c["documents_player_nav"]),
            ("GM nav entries", c["documents_gm_nav"]),
            ("Generated documents", c["generated_documents"]),
            ("Hand-authored/source documents", c["hand_authored_documents"]),
            ("Dynamic MkDocs documents", c["dynamic_documents"]),
            ("Documents requiring normalization", c["documents_requiring_normalization"]),
            ("Stub documents", c["stub_documents"]),
            ("Foundry folder records", c["foundry_folder_records"]),
            ("Organizational files/pages", c["organizational_files"]),
            ("Files with known exceptions", c["known_exception_files"]),
            ("Files with review flags", c["flagged_files"]),
            ("Files with unresolved local dependencies", c["unresolved_dependency_files"]),
            ("Duplicate-content groups", c["duplicate_content_groups"]),
        ]),
        "",
    ]

    for heading, key in [
        ("Files by source family", "by_source_family"),
        ("Files by audience", "by_audience"),
        ("Files by content scope", "by_content_scope"),
        ("Files by kind", "by_kind"),
        ("Files by authorship/source status", "by_authorship"),
    ]:
        lines += [f"## {heading}", "", md_table(list(c[key].items())), ""]

    lines += ["## MkDocs sites", ""]
    for site, meta in inv["mkdocs_sites"].items():
        lines += [
            f"- **{site}** — docs_dir `{meta['docs_dir']}`, nav entries {meta['nav_member_count']}"
        ]
    lines += [""]

    lines += ["## MkDocs / normalization features", ""]
    if inv["mkdocs_feature_counts"]:
        lines += [md_table(list(inv["mkdocs_feature_counts"].items())), ""]
    else:
        lines += ["None detected.", ""]

    lines += ["## Print-normalization flags", ""]
    if inv["normalization_flag_counts"]:
        lines += [md_table(list(inv["normalization_flag_counts"].items())), ""]
    else:
        lines += ["None detected.", ""]

    lines += ["## Generator reconciliation", ""]
    if inv["generator_reconciliation"]:
        lines += [
            "| Audience | Type | Source entities | Foundry folders | Generated pages | Missing | Organizational | Orphan |",
            "|---|---|---:|---:|---:|---:|---:|---:|",
        ]
        for r in inv["generator_reconciliation"]:
            lines.append(
                f"| {r['audience']} | {r['type']} | {r['source_entities']} | "
                f"{r.get('foundry_folders', 0)} | {r['generated_pages']} | "
                f"{len(r['missing_generated_pages'])} | "
                f"{len(r.get('organizational_generated_pages', []))} | "
                f"{len(r['orphan_generated_pages'])} |"
            )
        lines += [""]
        for r in inv["generator_reconciliation"]:
            if r["missing_generated_pages"] or r["orphan_generated_pages"] or r.get("organizational_generated_pages"):
                lines += [f"### {r['audience']} / {r['type']}", ""]
                if r["missing_generated_pages"]:
                    lines += ["**Missing generated pages:**", ""]
                    lines += [f"- `{x}`" for x in r["missing_generated_pages"]]
                    lines += [""]
                if r.get("organizational_generated_pages"):
                    lines += ["**Foundry folder / organizational generated pages (known exceptions):**", ""]
                    lines += [f"- `{x}`" for x in r["organizational_generated_pages"]]
                    lines += [""]
                if r["orphan_generated_pages"]:
                    lines += ["**Orphan generated pages:**", ""]
                    lines += [f"- `{x}`" for x in r["orphan_generated_pages"]]
                    lines += [""]
    else:
        lines += ["No generate-docs output sets detected.", ""]

    lines += ["## Title collisions", ""]
    if inv["title_collisions"]:
        for x in inv["title_collisions"]:
            lines.append(f"- **{x['title']}** — {x['classification']}: " + ", ".join(f"`{p}`" for p in x["paths"]))
        lines += [""]
    else:
        lines += ["None detected.", ""]

    lines += ["## Known exceptions", ""]
    if inv.get("known_exception_counts"):
        lines += [md_table(list(inv["known_exception_counts"].items())), ""]
    else:
        lines += ["None detected.", ""]

    lines += ["## Review flags", ""]
    if inv["review_flag_counts"]:
        lines += [md_table(list(inv["review_flag_counts"].items())), ""]
    else:
        lines += ["None detected.", ""]

    if inv["mkdocs_config_warnings"]:
        lines += ["## MkDocs configuration warnings", ""]
        lines += [f"- {w}" for w in inv["mkdocs_config_warnings"]]
        lines += [""]

    flagged = [i for i in inv["items"] if i["review_flags"]]
    lines += ["## Files requiring review", ""]
    if flagged:
        lines += [
            "| Path | Audience | Scope | Authorship | Flags |",
            "|---|---|---|---|---|",
        ]
        for i in flagged:
            flags = ", ".join(f"`{x}`" for x in i["review_flags"])
            lines.append(
                f"| `{i['path']}` | {i['audience']} | {i['content_scope']} | "
                f"{i['authorship']} | {flags} |"
            )
        lines += [""]
    else:
        lines += ["None.", ""]

    lines += [
        "## Phase 2 handoff",
        "",
        "Use this inventory to assign authority and publication disposition separately.",
        "Recommended disposition values remain `INCLUDE`, `EXCLUDE`, `REVIEW`, `GENERATE`,",
        "and `SUPERSEDED`.",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--version", action="version", version=f"%(prog)s {SCRIPT_VERSION} ({SCHEMA_VERSION})")
    p.add_argument("--repo-root", default=".", help="Cybermancy repository root (default: current directory)")
    p.add_argument(
        "--output-dir",
        default="build/rulebook/inventory",
        help="Output directory relative to repo root (default: build/rulebook/inventory)",
    )
    p.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero if MkDocs configs are missing or unresolved dependencies are found.",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(args.repo_root).expanduser().resolve()
    if not root.exists():
        print(f"ERROR: repository root does not exist: {root}", file=sys.stderr)
        return 2

    out_dir = Path(args.output_dir)
    if not out_dir.is_absolute():
        out_dir = root / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    inv = build_inventory(root)
    write_json(inv, out_dir / "rulebook-inventory.json")
    write_csv(inv, out_dir / "rulebook-inventory.csv")
    write_report(inv, out_dir / "rulebook-inventory-report.md")

    print(f"Wrote inventory to: {out_dir}")
    print(
        f"Files={inv['counts']['total_files']} "
        f"Documents={inv['counts']['documents']} "
        f"GeneratedDocs={inv['counts']['generated_documents']} "
        f"PlayerDocs={inv['counts']['documents_player_site']} "
        f"GMDocs={inv['counts']['documents_gm_site']}"
    )

    if args.strict:
        bad = bool(inv["mkdocs_config_warnings"]) or inv["counts"]["unresolved_dependency_files"] > 0
        if bad:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
